In [1]:
import numpy as np

In [2]:
N1=np.array([1,2,3,4])

In [4]:
N1.shape

(4,)

In [6]:
N2=np.array([(11,12,13,14),(15,16,17,18)])
print(N2)

[[11 12 13 14]
 [15 16 17 18]]


In [7]:
N2.shape

(2, 4)

In [8]:
N2.size

8

In [9]:
type(N2.shape)

tuple

In [10]:
N3=np.array([[(111,112,113),(114,115,116)],
             [(211,213,213),(214,215,216)],
             [(311,312,313),(314,315,316)]])
print(N3)

[[[111 112 113]
  [114 115 116]]

 [[211 213 213]
  [214 215 216]]

 [[311 312 313]
  [314 315 316]]]


In [11]:
N3.shape

(3, 2, 3)

In [12]:
N1

array([1, 2, 3, 4])

In [13]:
N1[0]

1

In [14]:
N1[0:3]

array([1, 2, 3])

In [15]:
N1[-1]

4

In [16]:
N1[-4:-2]

array([1, 2])

In [17]:
N2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [18]:
N2[0,0]

11

In [19]:
N2[1,3]

18

In [20]:
N2[0:,0:2]

array([[11, 12],
       [15, 16]])

In [21]:
N2[0:,1:3]


array([[12, 13],
       [16, 17]])

In [22]:
N3

array([[[111, 112, 113],
        [114, 115, 116]],

       [[211, 213, 213],
        [214, 215, 216]],

       [[311, 312, 313],
        [314, 315, 316]]])

In [23]:
N3[0,0,1]

112

In [24]:
N3[1,1,2]

216

In [25]:
N3[0:2,0:,0:2]

array([[[111, 112],
        [114, 115]],

       [[211, 213],
        [214, 215]]])

In [27]:
N3.reshape(3,3,2)

array([[[111, 112],
        [113, 114],
        [115, 116]],

       [[211, 213],
        [213, 214],
        [215, 216]],

       [[311, 312],
        [313, 314],
        [315, 316]]])

In [29]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(-5,20,2)

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
np.arange(-5,-20,-2)

array([ -5,  -7,  -9, -11, -13, -15, -17, -19])

In [34]:
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])